**Importer les libraries pertinentes**

Source : Prettenhofer, P., Grisel, O., Blondel, M., Amor, A. et Buitinck, L. [Classification of text documents using sparse features](https://scikit-learn.org/stable/auto_examples/text/plot_document_classification_20newsgroups.html#sphx-glr-auto-examples-text-plot-document-classification-20newsgroups-py). *scikit-learn*.

In [19]:
import multiprocessing
import pandas as pd
from os import listdir
from os import path

from IPython.display import clear_output

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_val_predict
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Naive Bayes
from sklearn.naive_bayes import MultinomialNB

# K plus proches voisins (kNN)
from sklearn.neighbors import KNeighborsClassifier

# Machines à vecteurs de support (SVM)
from sklearn import svm

# Régression Logistique
from sklearn.linear_model import LogisticRegression

# Forêt aléatoire 
from sklearn.ensemble import RandomForestClassifier

# Perceptron multicouche
#from sklearn.neural_network import MLPClassifier

**Charger les données**

In [20]:
folder = '../1-data/training_datasets/'
datasets = listdir(folder)
datasets = datasets[8:9]
datasets

['train_dataset_90pc.xlsx']

**Entraîner les modèles et sortir les résultats**

In [21]:
report = []
for file in datasets:
    ratio = file[14:-7]
    
    df = pd.read_excel(path.join(folder, file))
    X = df['text_post'].astype(str)
    y = df['category']

    # 5-fold cross-validation
    stratified_kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

    # Valeurs à tester pour le nombre de traits discriminants
    n_features_values = [100, 250, 500, 1000, 2500, 5000, 10000, 15000]

    # Antidictionnaire personnalisé
    with open('./utils/exclusion_v2.stop', encoding='utf-8') as f:
        custom_stopwords = [x.lower().strip('\n') for x in f.readlines()]
        custom_stopwords += list(ENGLISH_STOP_WORDS)

    # Algorithmes à tester
    algorithms = {
        'Naive Bayes' : MultinomialNB(), 
        'kNN (k=1)' : KNeighborsClassifier(n_neighbors=1),
        'kNN (k=2)' : KNeighborsClassifier(n_neighbors=2),
        'kNN (k=3)' : KNeighborsClassifier(n_neighbors=3),
        'Support Vector Machines (SVM)' :  svm.SVC(kernel="linear", C=1.0),
        'Logistic Regression': LogisticRegression(C=5, max_iter=1000),
        'Random Forest': RandomForestClassifier(),
        #'Multilayered Perceptron': MLPClassifier(hidden_layer_sizes=(100,), max_iter=500)
    }

    for n_features in n_features_values:
            tfidf_bow_vectorizer = TfidfVectorizer(stop_words=custom_stopwords, max_features=n_features)
            
            for algorithm in algorithms.keys():
                pipeline_algo = Pipeline([
                    ('tfidf', tfidf_bow_vectorizer),
                    ('classifier', algorithms[algorithm])
                ])

                # Validation croisée 
                scores = cross_val_score(pipeline_algo, X, y, cv=stratified_kfold, scoring='accuracy')
                predictions = cross_val_predict(pipeline_algo, X, y, cv=stratified_kfold)

                # Performances (rappel, précision, score F)
                results = {
                    '% Incels' : int(ratio),
                    'Algorithme' : algorithm,
                    'N traits discr.' : n_features,
                    'accuracy': scores.mean()       
                }
                results.update(classification_report(y, predictions, output_dict=True)['macro avg'])
                report.append(results)
                
                print(algorithm, f' | {ratio}% Incels | ', f'{n_features} traits discr.\n', classification_report(y, predictions))
                clear_output(wait=True)

Random Forest  | 90% Incels |  15000 traits discr.
               precision    recall  f1-score   support

       incel       0.91      0.98      0.94     45000
     neutral       0.40      0.09      0.15      4999

    accuracy                           0.90     49999
   macro avg       0.65      0.54      0.55     49999
weighted avg       0.86      0.90      0.87     49999

**Résultats**

In [22]:
# N.B. : Support = Nombre d'occurrence dans chaque classe
report = pd.DataFrame(report)
report['nb_posts_incels'] = (report['% Incels'].apply(lambda x: x/100) * report['support']).astype(int)
report['nb_posts_neutral'] = (report['% Incels'].apply(lambda x: 1-(x/100)) * report['support']).astype(int)

report = report.rename(columns={'support':'nb_posts_total'})
report['nb_posts_total'] = report['nb_posts_total'].astype(int)

# Réorganiser l'ordre des colonnes
report = report[['nb_posts_total', 'nb_posts_incels', 'nb_posts_neutral', '% Incels', 'Algorithme', 
                 'N traits discr.', 'accuracy', 'precision', 'recall','f1-score']]

report

,nb_posts_total,nb_posts_incels,nb_posts_neutral,% Incels,Algorithme,N traits discr.,accuracy,precision,recall,f1-score
0,49999,44999,4999,90,Naive Bayes,100,0.9000,0.4500,0.5000,0.4737
1,49999,44999,4999,90,kNN (k=1),100,0.8854,0.4999,0.5000,0.4849
2,49999,44999,4999,90,kNN (k=2),100,0.8986,0.5285,0.5006,0.4764
3,49999,44999,4999,90,kNN (k=3),100,0.8960,0.5158,0.5010,0.4794
4,49999,44999,4999,90,Support Vector Machines (SVM),100,0.9000,0.4500,0.5000,0.4737
5,49999,44999,4999,90,Logistic Regression,100,0.9000,0.4500,0.5000,0.4737
6,49999,44999,4999,90,Random Forest,100,0.8968,0.5274,0.5013,0.4793
7,49999,44999,4999,90,Naive Bayes,250,0.9000,0.4500,0.5000,0.4737
8,49999,44999,4999,90,kNN (k=1),250,0.8784,0.5161,0.5051,0.4972
9,49999,44999,4999,90,kNN (k=2),250,0.8982,0.5766,0.5032,0.4822
10,49999,44999,4999,90,kNN (k=3),250,0.8946,0.5313,0.5028,0.4842
11,49999,44999,4999,90,Support Vector Machines (SVM),250,0.9000,0.4500,0.5000,0.4737
12,49999,44999,4999,90,Logistic Regression,250,0.8999,0.5750,0.5001,0.4741
13,49999,44999,4999,90,Random Forest,250,0.8975,0.5681,0.5034,0.4831
14,49999,44999,4999,90,Naive Bayes,500,0.9000,0.4500,0.5000,0.4737
15,49999,44999,4999,90,kNN (k=1),500,0.8784,0.5276,0.5092,0.5039
16,49999,44999,4999,90,kNN (k=2),500,0.8978,0.5616,0.5028,0.4817
17,49999,44999,4999,90,kNN (k=3),500,0.8951,0.5414,0.5036,0.4854
18,49999,44999,4999,90,Support Vector Machines (SVM),500,0.9000,0.4500,0.5000,0.4737
19,49999,44999,4999,90,Logistic Regression,500,0.8994,0.6348,0.5036,0.4823
20,49999,44999,4999,90,Random Forest,500,0.8975,0.5954,0.5063,0.4892
21,49999,44999,4999,90,Naive Bayes,1000,0.9004,0.8139,0.5031,0.4801
22,49999,44999,4999,90,kNN (k=1),1000,0.8795,0.5406,0.5139,0.5110
23,49999,44999,4999,90,kNN (k=2),1000,0.8979,0.5753,0.5036,0.4834
24,49999,44999,4999,90,kNN (k=3),1000,0.8925,0.5502,0.5069,0.4937
25,49999,44999,4999,90,Support Vector Machines (SVM),1000,0.9002,0.7462,0.5027,0.4795
26,49999,44999,4999,90,Logistic Regression,1000,0.9001,0.7029,0.5191,0.5132
27,49999,44999,4999,90,Random Forest,1000,0.8961,0.6138,0.5142,0.5055
28,49999,44999,4999,90,Naive Bayes,2500,0.9013,0.8139,0.5102,0.4946
29,49999,44999,4999,90,kNN (k=1),2500,0.8763,0.5529,0.5224,0.5240
30,49999,44999,4999,90,kNN (k=2),2500,0.8975,0.6158,0.5095,0.4958
31,49999,44999,4999,90,kNN (k=3),2500,0.8912,0.5872,0.5184,0.5150
32,49999,44999,4999,90,Support Vector Machines (SVM),2500,0.9005,0.7579,0.5062,0.4869
33,49999,44999,4999,90,Logistic Regression,2500,0.9000,0.7036,0.5447,0.5571
34,49999,44999,4999,90,Random Forest,2500,0.8942,0.6343,0.5299,0.5335
35,49999,44999,4999,90,Naive Bayes,5000,0.9026,0.8234,0.5189,0.5117
36,49999,44999,4999,90,kNN (k=1),5000,0.8765,0.5648,0.5294,0.5337
37,49999,44999,4999,90,kNN (k=2),5000,0.8982,0.6365,0.5106,0.4976
38,49999,44999,4999,90,kNN (k=3),5000,0.8936,0.6021,0.5179,0.5133
39,49999,44999,4999,90,Support Vector Machines (SVM),5000,0.9016,0.7664,0.5184,0.5111
40,49999,44999,4999,90,Logistic Regression,5000,0.9016,0.7210,0.5619,0.5828
41,49999,44999,4999,90,Random Forest,5000,0.8931,0.6467,0.5394,0.5485
42,49999,44999,4999,90,Naive Bayes,10000,0.9030,0.8445,0.5199,0.5134
43,49999,44999,4999,90,kNN (k=1),10000,0.8777,0.5631,0.5270,0.5304
44,49999,44999,4999,90,kNN (k=2),10000,0.8984,0.6277,0.5077,0.4916
45,49999,44999,4999,90,kNN (k=3),10000,0.8954,0.5995,0.5124,0.5025
46,49999,44999,4999,90,Support Vector Machines (SVM),10000,0.9026,0.7755,0.5266,0.5263
47,49999,44999,4999,90,Logistic Regression,10000,0.9018,0.7227,0.5629,0.5842
48,49999,44999,4999,90,Random Forest,10000,0.8941,0.6486,0.5415,0.5516
49,49999,44999,4999,90,Naive Bayes,15000,0.9022,0.8369,0.5150,0.5040
50,49999,44999,4999,90,kNN (k=1),15000,0.8803,0.5640,0.5245,0.5267
51,49999,44999,4999,90,kNN (k=2),15000,0.8990,0.6384,0.5065,0.4887
52,49999,44999,4999,90,kNN (k=3),15000,0.8962,0.5979,0.5100,0.4976
53,49999,44999,4999,90,Support Vector Machines (SVM),15000,0.9030,0.7848,0.5282,0.5292
54,49999,44999,4999,90,Logistic Regression,15000,0.9023,0.7293,0.5597,0.5799
55,49999,44999,4999,90,Random Forest,15000,0.8957,0.6545,0.5396,0.5488

**Exporter les résultats de l'apprentissage**

In [23]:
report.sort_values(by='f1-score', ascending=False).to_csv(
    f'../3-results/results_training_90pc.csv', index=False
)

**Tester le système retenu sur de nouvelles données**

*On reproduit l'apprentissage pour le système retenu uniquement*

In [6]:
file_train = '../1-data/training_datasets/train_dataset_50pc.xlsx'

df_train = pd.read_excel(file_train)
df_train

,id_post,date_post,subreddit,author,text_post,category
0,g5cmft2,2020,ForeverAloneDating,luxiuo,Happy cake day my dude! Hope you get at least ...,incel
1,i3govkj,2022,ForeverAlone,Cassofalltrades,"Yeah, I always fantasized falling in love with...",incel
2,dkbpw8p,2017,Incels,shingis231,bro they're incels in denial. no fucking way a...,incel
3,dih6nor,2017,Incels,SmokeyMcBlunt,"lmao @ ""Posting on reddit""\n\nI wonder if thes...",incel
4,d8a5g44,2016,Incels,not_much_left,This is not true. Social research is fine so ...,incel
...,...,...,...,...,...,...
49995,esfzq10,2019,veloster,trav1th3rabb1,Yeah and what can do with this too?,neutral
49996,dzwtdlf,2018,gaming,jacksonh_56,I only have the snes classic but I want to own...,neutral
49997,hewyzgg,2021,insaneparents,Sheepgomoo123,What’s with these people thinking the “super s...,neutral
49998,esg0204,2019,hockey,Skylightt,I don't know about likely but Vatanen is defin...,neutral
49999,hv2cyx6,2022,KerbalSpaceProgram,trueppp,Mod the game until it naturally slows to a crawl.,neutral

In [7]:
# Système retenu : Naive Bayes ; 40% de données Incels ; 5 000 traits discriminants
X_train = df_train['text_post'].astype(str)
y_train = df_train['category']

ngram_values = (1, 2)

# Antidictionnaire personnalisé
with open('./utils/exclusion_v2.stop', encoding='utf-8') as f:
    custom_stopwords = [x.lower().strip('\n') for x in f.readlines()]
    custom_stopwords += list(ENGLISH_STOP_WORDS)

pipeline_nb = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words=custom_stopwords, ngram_range=ngram_values, max_features=15000)),
    ('nb', MultinomialNB())
])

pipeline_nb.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=15000, ngram_range=(1, 2),
                                 stop_words=['\ufeff&gt', 'a', 'â', 'ä', 'ã',
                                             'å', 'ªã', 'about', 'actually',
                                             'æ', 'again', 'against', "ain't",
                                             'all', 'allow', 'allows', 'almost',
                                             'alone', 'along', 'already',
                                             'also', 'although', 'always', 'am',
                                             'among', 'amongst', 'amp', 'an',
                                             'and', 'another', ...])),
                ('nb', MultinomialNB())])

In [8]:
stratified_kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
nb_predictions = cross_val_predict(pipeline_nb, X_train, y_train, cv=stratified_kfold)

# Performances en phase d'apprentissage du modèle retenu (rappel, précision, score F)
# Calculer et afficher les performances
accuracy_nb = accuracy_score(y_train, nb_predictions)
precision_nb = precision_score(y_train, nb_predictions, average='macro')
recall_nb = recall_score(y_train, nb_predictions, average='macro')
f1_nb = f1_score(y_train, nb_predictions, average='macro')

df = [
    {
        'Phase': 'Apprentissage',
        'Précision': precision_nb,
        'Rappel': recall_nb,
        'Mesure F': f1_nb,
        'Exactitude': accuracy_nb

    }
]

print(classification_report(y_train, nb_predictions))

              precision    recall  f1-score   support

       incel       0.72      0.81      0.76     25000
     neutral       0.78      0.68      0.73     25000

    accuracy                           0.75     50000
   macro avg       0.75      0.75      0.75     50000
weighted avg       0.75      0.75      0.75     50000

*On teste sur de nouvelles données*

In [9]:
file_test = '../1-data/test_dataset_10pc.xlsx'

df_test = pd.read_excel(file_test)
df_test

,date_post,id_post,author,subreddit,text_post,category
0,2021,hewyqir,KallystoNyx,FreeKarma4U,Bang!,neutral
1,2022,hv2cm15,Hopeful-Talk-1556,canada,I mean this is why you often get downvoted in ...,neutral
2,2021,hewyfkk,naughtyrpfan,HentaiAndRoleplayy,You playing m or f?,neutral
3,2016,d1l6201,greigmusic,IAmA,"Lol, google black pudding and your view will c...",neutral
4,2020,fzxnd3h,NorCalifornioAH,MapPorn,That's more a matter of Combined Statistical A...,neutral
...,...,...,...,...,...,...
9995,2021,hgdqoim,throwamay555,ForeverAlone,who said you were ugly?,incel
9996,2021,hmqkhx0,Admirable_Elk_965,ForeverAlone,Yeah I see this too when I walk out of class. ...,incel
9997,2022,iw0zptn,Resident_Setting3884,ForeverAlone,"this is exactly how i feel, im a cab driver, t...",incel
9998,2017,dfiq9mw,CALLMEMANTEE,Incels,I mean I'm not ok with it because its depressi...,incel
9999,2019,ejjhizf,neonfrogy,Braincels,men have preferences women have requirements,incel

*Vérifier qu'aucune donnée test n'était contenue dans les données d'appentissage*

In [10]:
validate = pd.concat([df_train, df_test])

validate[validate.duplicated(subset='id_post')]

Empty DataFrame
Columns: [id_post, date_post, subreddit, author, text_post, category]
Index: []

*Appliquer le classifieur aux nouvelles données*

In [11]:
X_test = df_test['text_post'].astype(str)
y_test = df_test['category']

y_pred_nb = pipeline_nb.predict(X_test)

In [12]:
# Calculer et afficher les performances
accuracy_nb = accuracy_score(y_test, y_pred_nb)
precision_nb = precision_score(y_test, y_pred_nb, average='macro')
recall_nb = recall_score(y_test, y_pred_nb, average='macro')
f1_nb = f1_score(y_test, y_pred_nb, average='macro')

df.append(
    {
        'Phase': 'Test',
        'Précision': precision_nb,
        'Rappel': recall_nb,
        'Mesure F': f1_nb,
        'Exactitude': accuracy_nb

    }
)

pd.set_option("display.precision", 4)
df = pd.DataFrame(df)
df.to_csv('../3-results/results_test.csv', index=False)
df

           Phase  Précision  Rappel  Mesure F  Exactitude
0  Apprentissage     0.7509  0.7468    0.7458      0.7468
1           Test     0.5976  0.7490    0.5804      0.7042

In [13]:
accuracy_nb

0.7042

In [14]:
precision_nb

0.5976497138745733

In [15]:
recall_nb

0.749

In [16]:
f1_nb

0.5803861060647741

In [17]:
print(classification_report(y_test, y_pred_nb))

              precision    recall  f1-score   support

       incel       0.23      0.81      0.35      1000
     neutral       0.97      0.69      0.81      9000

    accuracy                           0.70     10000
   macro avg       0.60      0.75      0.58     10000
weighted avg       0.90      0.70      0.76     10000

In [18]:
import pandas as pd
results = pd.read_csv('../3-results/results_training.csv')
results.sort_values(by='f_score', ascending=False)

KeyError: 'f_score'